FROM python:3.6-stretch

EXPOSE 5001

ENV ENV=production
ENV DEBUG=True
ENV MONGODB_HOST=mongo
ENV REDIS_URL=redis://redis
ENV SOCKET_HOST=0.0.0.0
ENV ORACLE_HOME=/app/oracle/instantclient_18_3
ENV LD_LIBRARY_PATH=/app/oracle/instantclient_18_3

WORKDIR /app
COPY . /app
COPY ./sources.list /etc/apt

RUN apt-get update 
RUN apt-get install -y libaio1 
RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com pipenv 
RUN pipenv install --system --ignore-pipfile --deploy --dev

CMD ["python", "run.py"]

